services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: secret_task_app_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/rails server -b 0.0.0.0
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/secret_task_app_development
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle
    depends_on:
      - db

volumes:
  postgres_data:
  bundle:
