FROM ruby:3.2.3

# 基本パッケージ（postgresに接続・native gem・JS系）
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  git \
  libpq-dev \
  nodejs \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# bundlerキャッシュを効かせる
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリ本体
COPY . .

# 開発環境
ENV RAILS_ENV=development

EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
